from django.conf import settings
from django.db import models

class GameConfig(models.Model):
    """Stores AI-generated game configurations. All fields are fully dynamic."""

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="game_configs",
        help_text="User who generated this config, if the request was authenticated.",
    )

    # Prompt that generated this config
    prompt = models.TextField(help_text="User prompt used to generate this config")

    # Dynamically generated by AI — no fixed choices
    template = models.CharField(
        max_length=100,
        help_text="Game type e.g. runner, shooter, rpg, survival — AI generated"
    )
    title = models.CharField(
        max_length=300,
        help_text="AI-generated unique game title"
    )

    # All nested config stored as flexible JSON
    difficulty = models.JSONField(
        default=dict,
        help_text="Difficulty settings: level (string), enemySpeed, playerLives, spawnRate, extraMechanics"
    )
    theme = models.JSONField(
        default=dict,
        help_text="Theme settings: style, primaryColor, accentColor, environment, atmosphere"
    )
    rules = models.JSONField(
        default=dict,
        help_text="Game rules: objective, timeLimit, scoring, specialMechanics, playerAbilities"
    )
    assets = models.JSONField(
        default=dict,
        help_text="Asset descriptions: playerSprite, background, enemies, powerUps, soundtrack"
    )

    # Full raw config stored as well for reference
    raw_config = models.JSONField(default=dict)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        level = self.difficulty.get('level', 'N/A') if isinstance(self.difficulty, dict) else 'N/A'
        return f"{self.title} ({self.template}) [{level}]"
