# Generated by Django 6.0.4 on 2026-04-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='User prompt used to generate this config')),
                ('template', models.CharField(help_text='Game type e.g. runner, shooter, rpg, survival — AI generated', max_length=100)),
                ('title', models.CharField(help_text='AI-generated unique game title', max_length=300)),
                ('difficulty', models.JSONField(default=dict, help_text='Difficulty settings: level (string), enemySpeed, playerLives, spawnRate, extraMechanics')),
                ('theme', models.JSONField(default=dict, help_text='Theme settings: style, primaryColor, accentColor, environment, atmosphere')),
                ('rules', models.JSONField(default=dict, help_text='Game rules: objective, timeLimit, scoring, specialMechanics, playerAbilities')),
                ('assets', models.JSONField(default=dict, help_text='Asset descriptions: playerSprite, background, enemies, powerUps, soundtrack')),
                ('raw_config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
